export { Billing } from './Billing';
export { Business } from './Business';
export {Button} from './Button';
export { CardDeal } from './CardDeal';
export { Client } from './Client';
export { CTA } from './CTA';
export {FeedbackCard} from './FeedbackCard';
export { Footer } from './Footer';
export {GetStarted} from './GetStarted';
export { Hero } from './Hero';
export { Navbar } from './Navbar';
export { Stats } from './Stats';
export { Testimonials } from './Testimonial';
